---
names:
- CECEP JUNCHENG (SHANGHAI) ENVIRONMENTAL TECHNOLOGY CO., LTD.
country: China
source: wb-data
ref_number: 595172
ref_type: World Bank SUPP ID
remark: Controlled Affliiate of a Sanctioned Entity.
address:
- street: NO. 599 LIUYUAN ROAD, PUTUO DISTRICT, SHANGHAI, SECOND FLOOR OF BUILDING
    8 C
  city: SHANGHAI
  state: 
  country: China
  zip: 
