---
names:
- CECEP LIUHE TALROAD ENVIRONMENTAL TECHNOLOGY CO., LTD.
country: China
source: wb-data
ref_number: 168587
ref_type: World Bank SUPP ID
remark: 2006 Procurement Guidelines, para. 1.14(a)(ii)
address:
- street: FLOOR 6, BLOCK A, JIENENG BUILDING, 42 XIZHIMEN NORTH ST., HAIDIAN DISTRICT,
    100082
  city: BEIJING
  state: 
  country: China
  zip: 
