---
names:
- CENTER FOR ENVIRONMENTAL STUDIES AND MANAGEMENT, INC. (CESM)
country: Philippines
source: wb-data
ref_number: 336548
ref_type: World Bank SUPP ID
remark: 2006 Consultant Guidelines, para. 1.22(a)(ii)
address:
- street: SUITE 210, QUADSTAR BLDG. NO. 80 ORTIGAS AVENUE, GREENHILLS, SAN JUAN CITY,
    1502
  city: METRO MANILA
  state:
  country: Philippines
  zip:
