---
names:
- CHINA RAILWAY FIRST GROUP MUNICIPAL & ENVIRONMENTAL PROTECTION ENGINEERING CO.,
country: China
source: wb-data
ref_number: 438729
ref_type: World Bank SUPP ID
remark: Controlled Affiliate of a Sanctioned Entity.
address:
- street: RENJIAZHUANG, DUNHUANG ROAD, QILIHE DISTRICT
  city: LANZHOU CITY, GANSU PROVINCE
  state: 
  country: China
  zip: 
