---
names:
- CNE ENVIRONMENTAL & WASTE SERVICES LTD.
country: Nigeria
source: wb-data
ref_number: 402110
ref_type: World Bank SUPP ID
remark: Procurement Guidelines, 1.16(a)(ii)
address:
- street: NO. 2, PINTO AVENUE, GANA SAPELE
  city: DELTA STATE
  state: ''
  country: Nigeria
  zip: ''
