---
names:
- HEBEI HAIKUO ENVIRONMENTAL TECHNOLOGY CO., LTD.
country: China
source: wb-data
ref_number: 888137
ref_type: World Bank SUPP ID
remark: 'Cross Debarment: ADB'
address:
- street: FLOOR 23, HEBEI CONSTRUCTION BUSINESS CENTER ,NO 125 , LUGANG ROAD, JINGXIU
    DISTRICT
  city: BAODING CITY, HEBEI PROVINCE
  state:
  country: China
  zip:
