---
names:
- NATURE ENVIRONMENTAL AND MARINE SERVICES LLC
country: United States
source: wb-data
ref_number: 627420
ref_type: World Bank SUPP ID
remark: Controlled Affiliate of a Sanctioned Entity.
address:
- street: 2002 TIMBERLOCH PLACE, SUITE 200
  city: SPRING
  state: 
  country: United States
  zip: '77380'
