---
names:
- PRODUCTIONSEKONOMI I STOCKHOLM AB
country: Sweden
source: wb-data
ref_number: 113342
ref_type: World Bank SUPP ID
remark: Consultant Guidelines 1.25(a)(i)
address:
- street: ''
  city: STOCKHOLM
  state: ''
  country: Sweden
  zip: ''
