---
names:
- RAMKY ENERGY AND ENVIRONMENT LTD.
country: India
source: wb-data
ref_number: 692016
ref_type: World Bank SUPP ID
remark: Controlled Affiliate of a Sanctioned Entity.
address:
- street: LEVEL 11B, AUROBINDO GALAXY, HYDERABAD KNOWLEDGE CITY, HITECH CITY ROAD
  city: HYDERABAD 500081 TELANGANA
  state: 
  country: India
  zip: 
