---
names:
- RAMKY ENVIRONMENTAL TECHNOLOGY (SHENZHEN) CO LTD, CHINA
country: China
source: wb-data
ref_number: 627392
ref_type: World Bank SUPP ID
remark: Controlled Affiliate of a Sanctioned Entity.
address:
- street: 8TH FLOOR, CHANGSHENG BUILDING, HUAQIANG NORTH ROAD, FUTIAN DISTRICT
  city: SHENZHEN
  state: 
  country: China
  zip: 
