---
names:
- RAMKY CLEANTECH ENVIRONMENTAL SERVICES – SOLE PROPRIETORSHIP L.L.C.
country: United Arab Emirates
source: wb-data
ref_number: 637821
ref_type: World Bank SUPP ID
remark: Controlled Affiliate of a Sanctioned Entity
address:
- street: 'PLOT NO: C126, SECTOR E11'
  city: ABU DHABI ISLAND
  state: 
  country: United Arab Emirates
  zip: 
