---
names:
- RE SUSTAINABILITY ENVIRONMENTAL SERVICES LLC
country: United Arab Emirates
source: wb-data
ref_number: 687512
ref_type: World Bank SUPP ID
remark: Controlled afilliate of a sanctioned entity
address:
- street: UNIT NO. 6, ALJAWIS, HOSUN STREET
  city: EMIRATE OF RAS AL KHAIMAH
  state: 
  country: United Arab Emirates
  zip: 
