---
names:
- SFC VIETNAM INVESTMENT DEVELOPMENT FOR ENVIRONMENT CORPORATION
country: Viet Nam
source: wb-data
ref_number: 313220
ref_type: World Bank SUPP ID
remark: Consult. Guidelines, 1.22(a)(ii); Proc. Guidelines, 1.14(a)(ii)-(iii)
address:
- street: TOWER CENTER OFFICE BUILDING, NO. 83A LY THUONG KIET STREET, DISTRICT HOAN
    KIEM
  city: HANOI
  state: 
  country: Viet Nam
  zip: 
