---
names:
- SOCIAL AND ENVIRONMENTAL DEVELOPMENT JOINT STOCK COMPANY
country: Viet Nam
source: wb-data
ref_number: 188749
ref_type: World Bank SUPP ID
remark: Consultant Guidelines 1.22(a)(ii)
address:
- street: NO. 20, 445 LAC LONG QUAN STREET,TAY HO DISTRICT
  city: HANOI
  state:
  country: Viet Nam
  zip:
