---
names:
- TATVA GLOBAL ENVIRONMENT PVT. LTD.
country: India
source: wb-data
ref_number: 343109
ref_type: World Bank SUPP ID
remark: Terms of Negotiated Resolution Agreement
address:
- street: UNIPHOS HOUSE, C.D. MARG., 11TH ROAD, MADHU PARK
  city: KHAR WEST, MUMBAI - 400 052
  state: 
  country: India
  zip: 
