---
names:
- UPL ENVIRONMENTAL ENGINEERS LIMITED
country: India
source: wb-data
ref_number: 344017
ref_type: World Bank SUPP ID
remark: Terms of Negotiated Resolution Agreement
address:
- street: SF-203, CONCORDE BUILDING, ALKAPURI PETROL PUMP, R. C. DUTT ROAD
  city: VADODARA, VADODARA, GUJARAT, 393007
  state: 
  country: India
  zip: 
