---
names:
- VIETNAM WATER AND ENVIRONMENT INVESTMENT CORPORATION – JSC
country: Viet Nam
source: wb-data
ref_number: 411185
ref_type: World Bank SUPP ID
remark: Fraudulent Practices
address:
- street: 52 QUOC TU GIAM, VAN MIEU WARD, DONG DA DISTRICT
  city: HANOI
  state:
  country: Viet Nam
  zip:
