---
names:
- VIWASEEN-PHUONG HUONG ENVIRONMENT INVESTMENT AND DEVELOPMENT JSC
country: Viet Nam
source: wb-data
ref_number: 411207
ref_type: World Bank SUPP ID
remark: Controlled Affiliate of a Sanctioned Entity
address:
- street: KM9, CHU SE DISTRICT
  city: GIA LAI PROVINCE
  state: 
  country: Viet Nam
  zip: 
